name: doxie
description: "A new Flutter project."
publish_to: "none" # Prevent accidental publishing to pub.dev

version: 1.0.0+1
environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  permission_handler: ^10.2.0
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.0
  shared_preferences: ^2.0.6
  flutter_pdfview: ^1.0.4 # Update version if needed
  path_provider: any
  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.3
  http: ^1.2.2
  json_annotation: ^4.4.0
  # pdf_text: ^3.0.0
  # pdf: ^3.11.0
  # pdfx: ^2.0.0
  # flutter_pdf_viewer: ^0.6.1
  # syncfusion_flutter_pdfviewer: ^22.1.34

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  lint: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/Doxie_logo.png
    - lib/assets/1-purchase order sal011742.pdf
    - lib/assets/2-invoice for accouting.PDF
    - lib/assets/DoNotReplywal-mart.com_20230102_160505 (1)-2.pdf
    - lib/assets/chevron-left
